#! /usr/bin/env node

var source    = "bower_components/cssowl/src";
var target    = "source/docs";
var options = {
  helpers: "resources/docs/helpers.js",
  template: "resources/docs/template.hbs",
  filter: function(filename) { return (filename != '_imports.yml') },
  filename: function(item, syntax) { return "_" + item.basename + ".haml"; }
};
require('librarianowl').compile(source, target, options);
